import Sidebar from '@/components/sidebar'
import './globals.css'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<head />
			<body>
				<div className='flex'>
					<Sidebar />
					{/* Client provider */}
					<div className='bg-dark flex-1'>{children}</div>
				</div>
			</body>
		</html>
	)
}
